# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hcolumbu <hcolumbu@student.21-school.ru    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/26 09:09:32 by hcolumbu          #+#    #+#              #
#    Updated: 2022/03/14 10:15:22 by hcolumbu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRCS =	ft_isalpha.c	ft_isdigit.c		ft_isalnum.c	ft_isascii.c\
		ft_isprint.c	ft_strlen.c			ft_memset.c		ft_bzero.c\
		ft_memcpy.c		ft_memmove.c		ft_strlcpy.c	ft_strlcat.c\
		ft_toupper.c	ft_tolower.c		ft_strchr.c		ft_strrchr.c\
		ft_strncmp.c	ft_memchr.c			ft_memcmp.c		ft_strnstr.c\
		ft_atoi.c		ft_calloc.c			ft_strdup.c		ft_substr.c\
		ft_strjoin.c	ft_strtrim.c		ft_split.c		ft_itoa.c\
		ft_strmapi.c	ft_striteri.c		ft_putchar_fd.c	ft_putstr_fd.c\
		ft_putendl_fd.c	ft_putnbr_fd.c		ft_strequ.c		ft_atoi_double.c\
		ft_lstnew.c		ft_lstadd_front.c	ft_lstsize.c\
		ft_lstlast.c	ft_lstadd_back.c	ft_lstdelone.c\
		ft_lstclear.c	ft_lstiter.c		ft_lstmap.c

OBJS = $(SRCS:%.c=%.o)
HEADER = libft.h
CC = cc
CFLAGS = -Wall -Wextra -Werror
LIB = ar rcs
RM = rm -f

.PHONY: all clean fclean re

all: $(NAME)

$(NAME): $(OBJS)
	$(LIB) $(NAME) $? 

%.o: %.c $(HEADER) Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all
